### ISSUE TITLE
Is a KeyboardClosed event possible?

### ISSUE THREAD

**Issue by jb455** [AlexeiScherbakov/osklib#3]
Hi,
When I call the keyboard to open I have to move some UI around so the user can see what they're typing, then when the user taps off the field I close the keyboard and move the UI back. However, if the user closes the keyboard manually by pressing the x on it, the UI doesn't know it has to move back.
Would it be possible to make a KeyboardClosed event I can subscribe to to move the UI back when the keyboard is closed manually?

Thanks!

**Comment by AlexeiScherbakov** [comment]
Yes, it is possible. I added 'OnScreenKeyboardWatcher' class which implements KeyboardOpened & KeyboardClosed events.

**Comment by jb455** [comment]
That's perfect, thanks so much!
For future reference, the events occur on a separate thread without access to UI so if you want to change UI stuff within the events, it needs to be invoked like so:
```
private void Watcher_KeyboardClosed(object sender, EventArgs e)
{
    Dispatcher.Invoke((Action)(() =>
    {
        //Change UI stuff
    }));
}
```

**Comment by AlexeiScherbakov** [comment]
In version 1.3 DispatcherOnScreenKeyboardWatcher and WinFormsKeyboardWatcher classes implement same logic without needing invoke call
