### ISSUE TITLE
Use Osklib

### ISSUE THREAD

**Issue by KevinLenoir** [AlexeiScherbakov/osklib#4]
Hi,

I need to catch the Show and Hide events of the OSK, and your lib is doing the job. Unfortunately it appears that the NuGet does not include the Osklib.WPF. Moreover, as I see no license, I can't use your work, especially in this commercial context of mine. Could you add a licence to your code, for instance MIT or Apache 2, or packaging Osklib.WPF ?

Thanks,
Kévin.

**Comment by AlexeiScherbakov** [comment]
Ok. I'll add Osklib.Wpf to NuGet.

чт, 28 Июн 2018, 17:23 Kévin Lenoir <notifications@github.com>:

**Comment by KevinLenoir** [comment]
Great thanks ! And about the licence ? (Sorry I said "or" but even for the NuGet, I need to know the permissions)

**Comment by AlexeiScherbakov** [comment]
It can be added without crazy amount of comments in each file in project?

чт, 28 Июн 2018, 18:10 Kévin Lenoir <notifications@github.com>:

**Comment by KevinLenoir** [comment]
It appears to be pretty easy on GitHub, you just need to set the license in the repository "Code" tab. You can click on the "LICENSE" word where it says : "We recommend every repository include a README, LICENSE, and .gitignore. ". You can check the different licenses here : https://choosealicense.com/

For example, this website says that "The MIT License is a permissive license that is short and to the point. It lets people do anything they want with your code as long as they provide attribution back to you and don’t hold you liable."

Of course, there are other types of license, you can choose the one you want. Also check the types of license you can add depending on you GitHub account level.

**Comment by AlexeiScherbakov** [comment]
I added MIT licence. Tomorrow I'll add new version to NuGet

**Comment by KevinLenoir** [comment]
Yay, super nice, thank you very much :)

**Comment by KevinLenoir** [comment]
Hello ! Sorry to bother you again, still no NuGet ? :)

**Comment by AlexeiScherbakov** [comment]
.
