### ISSUE TITLE
Not working after NuGet Update

### ISSUE THREAD

**Issue by digitaico** [AlexeiScherbakov/osklib#5]
Hi Alexei,  just updated the NuGet package which by the way is version 1.2 and OskLib stopped working.  Can you tell me how to update to Version 1.4 without NuGet.
By the way about a month ago,  OskLib stopped working on Windows 10 pc's.

**Comment by AlexeiScherbakov** [comment]
Can you check current version from Github? I don't place it in nuget
because I was on holidays and a lot of work after :-)
If current version from source code is working - I will post it to NuGet
feed

чт, 19 Июл 2018, 18:03 datelligence <notifications@github.com>:

**Comment by digitaico** [comment]
Alexei Osklib was working as expected,  then It does not work,  I'm afraid is related to Windows 10 updates.  Mine is version 18.  Github v is 1.4.
I'll install github version on my windows machine.
