### ISSUE TITLE
Windows 10 (1809) - IsOpened() always return false

### ISSUE THREAD

**Issue by AlanGusLive** [AlexeiScherbakov/osklib#6]
Hi,

With Windows 10 (1709) IsOpened() works but with Windows 10 (1809) IsOpened() always return false.
I think the bug is in the file Osklib\Interop\NativeMethods.cs in the function FindTextInputWindow().
I opened my On-Screen Keyboard and I analysed all the Windows's computer with "Microsoft Spy++".

This is a resume :
Window 0001099A "" **ApplicationFrameWindow**
-->Window 000109A6 "" ApplicationFrameTitleBarWindow
-->Window 000109A2 "" ApplicationFrameTitleBarWindow
-->Window 000109AA "" ApplicationFrameInputSinkWindow
Window 00010998 "Default IME" IME
Window 00010996 "Microsoft Text Input Application" Windows.UI.Core.CoreWindow
Window 00010980 "Default IME" IME
Window 00010984 "Default IME" IME
Window 00010982 "" **ApplicationFrameWindow**
-->Window 0001097E "Microsoft Text Input Application" Windows.UI.Core.CoreWindow
		
As you can see I have 2 entry with "ApplicationFrameWindow" and the first is NOT the window wanted. In the program as soon as an entry "ApplicationFrameWindow" is found there is a return so the second entry is never checked.

I updated the function by adding "if (IsValidHandle(textInput))"

BEFORE :
```
internal static IntPtr FindTextInputWindow()
{
	// enumerating Windows Store Container windows and try to find Window with caption 'Microsoft Text Input Application'
	IntPtr lastProbed = IntPtr.Zero;
	do
	{
		lastProbed = FindWindowEx(IntPtr.Zero, lastProbed, ApplicationFrameHostClassName, null);
		if (IsValidHandle(lastProbed))
		{
			var textInput = FindWindowEx(lastProbed, IntPtr.Zero, CoreWindowClassName, TextInputApplicationCaption);
			return textInput;
		}
	} while (IsValidHandle(lastProbed));

	return IntPtr.Zero;
}
```

AFTER :
```
internal static IntPtr FindTextInputWindow()
{
	// enumerating Windows Store Container windows and try to find Window with caption 'Microsoft Text Input Application'
	IntPtr lastProbed = IntPtr.Zero;
	do
	{
		lastProbed = FindWindowEx(IntPtr.Zero, lastProbed, ApplicationFrameHostClassName, null);
		if (IsValidHandle(lastProbed))
		{
			var textInput = FindWindowEx(lastProbed, IntPtr.Zero, CoreWindowClassName, TextInputApplicationCaption);
			if (IsValidHandle(textInput))
			{
				return textInput;
			}
		}
	} while (IsValidHandle(lastProbed));

	return IntPtr.Zero;
}
```

Now the function IsOpened() works with my Windows 10 (1809).
Are you agree with this change ?

Regard,
AlanGusLive

**Comment by yinghualuowu** [comment]
Window(1903).if opened the keyboard and hide it after,IsOpened() always return true.....
Is there a way to get keyboard status?

**Comment by AlexeiScherbakov** [comment]
I'll check it tomorrow

пн, 21 окт. 2019 г., 10:58 Yinghualuowu <notifications@github.com>:

**Comment by zellhwang** [comment]
Hi Alexei,
  
  Any updates ? Since 1903 update, KeyboardOpened and KeyboardClosed events no longer works. Do let me know if it is possible to make it work, as we will have to find alternative means if this can't be fixed. Thanks, much appreciated. :)

**Comment by AlexeiScherbakov** [comment]
Please check lastest version from this repository. If it works for you - I'll update NuGet package

**Comment by zellhwang** [comment]
Hi Alexei,

  Has anything been updated ? I downloaded the package and didn't see any update files. I compiled the dll and tested, it seems the same.

**Comment by AlexeiScherbakov** [comment]
I updated only source - for 10.0.18362.418 all is working. New code have
some breaking changes (now it use WinRT/COM for all new versions of Windows
10), so I will publish package when I'll have feedback about stability

пн, 4 нояб. 2019 г., 13:36 zellhwang <notifications@github.com>:

**Comment by AlanGusLive** [comment]
Hi Alexei,

I downloaded a zip file of the lastest source code from the Master Branch, but there is no change in the source code. As I want to test, where can I find the updated source code?
I checked, there is only one branch in your project.

Regards,
AlanGusLive

**Comment by AlexeiScherbakov** [comment]
May be notebook goes sleep faster then git push. I'll check it in 2-3 hours

пн, 4 нояб. 2019 г., 20:48 Fruity Mix Free <notifications@github.com>:

**Comment by zellhwang** [comment]
Hi Alexei,

  I have tested the new codes and it works under Windows 10 (1809). Thanks for the update, much appreciated. :)

**Comment by yinghualuowu** [comment]
After using new codes, everything was in expected state.Thank you! Glad that it helped~

**Comment by AlanGusLive** [comment]
Hi Alexei,

I tested the new source code with the ConsoleTester. This is the result:

Windows 1909 (10.0.18363.418) : OK
Windows 1903 (10.0.18362.449) : OK
Windows 1809 (10.0.17763.805) : OK
Windows 1709 (10.0.16299.1451) : Problem, the virtual keyboard is NOT displayed after the call of OnScreenKeyboard.Show().

For this problem, in the file Osklib\NewWindows10OnScreenKeyboardController.cs the fonction IsOpened() return true but my virtual keyboard is hide when I start the program.
Line 54, the call of _inputHostManagerBroker.Instance.GetIhmLocation(out var ret, out displayMode); as a ret with the four values to zero and the displayMode is DisplayMode.Docked => so the function return true which is wrong.
After the line 54, I added a new test :
```
if (ret.Bottom == 0 && ret.Left == 0 && ret.Right == 0 && ret.Top == 0)
{
	return false;
}
```

And it works (the OnScreenKeyboard.Show() and after the OnScreenKeyboard.Close()). I think the test must be added line 64 too.

Have you test with Windows 1709 ? Can you tell me how to fix with a better solution?

Regards,
AlanGusLive

**Comment by AlexeiScherbakov** [comment]
You can look OnScreenKeyboard.cs for a version check and try to change
'version.Build>=16299' from >= to > . For new versions it use WinRT/COM
check. For old versions it use WinAPI mode. Between simple WinAPI check and
pure WinRT check there are many versions with strange behavior. So WinAPI
check becomes something crazy :-)
WinRT check was introduced to detect docking/floating mode and in new
versions it also can be used to detect opened/closed states.

чт, 7 нояб. 2019 г., 22:22 Fruity Mix Free <notifications@github.com>:

**Comment by AlanGusLive** [comment]
Hi Alexei,

As you said, with the file OnScreenKeyboard.cs, I changed 'version.Build>=16299' from >= to > and now it works with Windows 1709 (10.0.16299.1451).
Well done :-)

Can you update your source code with this fix to close this issue ?

Regards,
AlanGusLive

**Comment by AlexeiScherbakov** [comment]
Well I'm glad to see, that it is working :-D
This code is full of dirty hacks )))


пт, 8 нояб. 2019 г., 21:06 Fruity Mix Free <notifications@github.com>:

**Comment by AlexeiScherbakov** [comment]
Version 1.6 on NuGet

**Comment by AlanGusLive** [comment]
Hi Alexei,

Thanks for the NuGet version.
I close this Issue.

Regards,
AlanGusLive
