### ISSUE TITLE
Higher authority error in WPF with .NetCore3.1

### ISSUE THREAD

**Issue by ypeng-ming** [AlexeiScherbakov/osklib#8]
When I use OnScreenKeyBoard.Open(), I got an error says : _System.ComponentModel.Win32Exception: operation required need to upgrade_.  And I ran program with ADMIN, it still don't work. 
I tried with .Net Framework4.7.2, it works fine. does anyone know how to solve this problem with .NetCore? Please.

**Comment by AlexeiScherbakov** [comment]
I finded solution for this. 1.7.0-beta.1 version will fix it and also brings 1909 Windows support

**Comment by ypeng-ming** [comment]
Thanks, you are so great, I couldn't find solution in last 2 days...
